### ISSUE TITLE
Question about unlocker-dapp

### ISSUE THREAD

**Issue by agoora** [markdreyer/unlocker-dapp#1]
I want to know if the application (unlockmex.com) works today only on ELROND testnet?

**Comment by markdreyer** [comment]
Hi- it's only testnet at the moment

**Comment by agoora** [comment]
When is the mainnet version scheduled to be released?
Thanks again.

**Comment by markdreyer** [comment]
Thanks for the interest, it should be ready for mainnet by the end of the year. Will keep you posted!

**Comment by markdreyer** [comment]
Just released an alpha version on mainnet for testing. It is funded with a small amount of liquidity for testing purposes.
